# Generated by Django 5.0.6 on 2024-06-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profileuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='age',
            field=models.IntegerField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='bio',
            field=models.TextField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='firstname',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='lastname',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
