# Generated by Django 5.0.6 on 2024-06-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profileuser_age_alter_profileuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='age',
            field=models.IntegerField(blank=True, default='20', null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='bio',
            field=models.TextField(blank=True, default=' szkfngj;zksjgn', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='firstname',
            field=models.CharField(blank=True, default='sjdkhf ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='lastname',
            field=models.CharField(blank=True, default=' slzkfgj', max_length=100, null=True),
        ),
    ]
