# Generated by Django 5.0.6 on 2024-06-15 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('about', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='media\\%Y-%m-%d')),
                ('Available', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofood', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
