# Generated by Django 5.0.6 on 2024-06-15 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paied', models.BooleanField(default=False)),
                ('Create', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uorder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('num', models.IntegerField(default=1)),
                ('foods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forderitem', to='home.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oorderitem', to='orders.order')),
            ],
        ),
    ]
